// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wddnuslcjbnharznwmku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZG51c2xjamJuaGFyem53bWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDE3NzAsImV4cCI6MjA2MzExNzc3MH0.ob9AK3YIFWNw6115IGwnqKnNb7uSlbYImKnEVMWv9Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);